Repository psgstellar/Stellar, pull requests merged in 2021-02, with the labels that each got.

#46 resolve Issue-#44-github
  Stellar/src/main/webapp/WEB-INF/jsp/admin/settings.jsp
  Stellar/src/main/webapp/WEB-INF/jsp/member/settings.jsp
Labels: enhancement

#49 fixed bug - #48
  PyStellar/stellar/commit/service/commitservice.py
Labels: enhancement, fix

#52 close #51
  Stellar/src/main/java/com/psg/mapper/CommitMapper.java
  Stellar/src/main/java/com/psg/service/MemberService.java
  Stellar/src/main/java/com/psg/service/impl/MemberServiceImpl.java
  Stellar/src/main/java/com/psg/vo/GithubVO.java
  Stellar/src/main/java/com/psg/web/MainController.java
  Stellar/src/main/resources/egovframework/sqlmap/mapper/CommitSQL.xml
  Stellar/src/main/webapp/WEB-INF/jsp/admin/settings.jsp
  Stellar/src/main/webapp/WEB-INF/jsp/member/settings.jsp
Labels: development
